---
 - name: Download resolvconf package
   apt: name=resolvconf

 - name: Set nameservers and search domain
   template: src="default.j2" 
             dest="/etc/resolvconf/resolv.conf.d/head"
   notify: restart resolvconf 

 - name: Update resolv.conf
   command: resolvconf -u
