---
- name: Provision new host
  hosts: virtual_machines
  remote_user: xr34ct
  become: yes
  
  roles:
    - first_time
    - common
    - hostname
    - fail2ban
    - unattended
    - resolvconf
    - ssh
    - postfix
