---
 - name: Download postfix package
   apt: name=postfix

 - name: Download mailutils
   apt: name=mailutils

 - name: Set mailname
   template: src="mailname.j2" 
             dest="/etc/mailname"
   notify: restart postfix

 - name: Send mail to logs
   mail: host='localhost' 
         port='25' 
         to="logs <logs@avdagic.net>" 
         subject='Ansible-report' 
         body='System {{ ansible_hostname }} has been successfully provisioned.'
